#!/bin/bash

# Re-git
rm -rf .git;
git init .

# Rename files with project name
mv ogl-base $1;
mv $1/ogl-base.cpp $1/$1.cpp

# Replace with project name
sed -i -e "s/ogl-base/$1/g" CMakeLists.txt
sed -i -e "s/ogl-base/$1/g" $1/$1.cpp

# Git commit
git add .
git commit -m "Created OpenGL App";

# CMake
mkdir -p build
cd build
cmake -G "Visual Studio 15 2017" ..
cd ..

